<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1713995452" />
    <testcase name="testFirstCacheLine" classname="functional_tests" file="/home/hakam/repos/ChaosCore/cocotb/functional_tests/instruction_cache_tests/functional_tests.py" lineno="90" time="0.0014951229095458984" sim_time_ns="12.001" ratio_time="8026.7648387816935">
      <failure message="Test failed with RANDOM_SEED=1713995452" />
    </testcase>
    <testcase name="testFirstCacheLineUnaligned" classname="functional_tests" file="/home/hakam/repos/ChaosCore/cocotb/functional_tests/instruction_cache_tests/functional_tests.py" lineno="145" time="0.0006718635559082031" sim_time_ns="12.001" ratio_time="17862.25773740241">
      <failure message="Test failed with RANDOM_SEED=1713995452" />
    </testcase>
    <testcase name="testLRU" classname="functional_tests" file="/home/hakam/repos/ChaosCore/cocotb/functional_tests/instruction_cache_tests/functional_tests.py" lineno="208" time="0.0009355545043945312" sim_time_ns="14.001000000000001" ratio_time="14965.45624464832">
      <failure message="Test failed with RANDOM_SEED=1713995452" />
    </testcase>
    <testcase name="testReads" classname="functional_tests" file="/home/hakam/repos/ChaosCore/cocotb/functional_tests/instruction_cache_tests/functional_tests.py" lineno="330" time="0.0019402503967285156" sim_time_ns="52.001000000000005" ratio_time="26801.179934136155">
      <failure message="Test failed with RANDOM_SEED=1713995452" />
    </testcase>
    <testcase name="testPacketMuxing" classname="functional_tests" file="/home/hakam/repos/ChaosCore/cocotb/functional_tests/instruction_cache_tests/functional_tests.py" lineno="445" time="0.0022530555725097656" sim_time_ns="58.00099999999999" ratio_time="25743.262042751317">
      <failure message="Test failed with RANDOM_SEED=1713995452" />
    </testcase>
  </testsuite>
</testsuites>
